DefaultContentLanguage = "en"
Paginate = 6
SectionPagesMenu = "main"
baseURL = "https://ryanjbartley.github.io/gphugo/"
enableRobotsTXT = true
languageCode = "en-us"
theme = "novela"
title = "Developing Github Pages with Hugo and Forestry"
[params]
description = "A blog while I work"
[params.share]
facebook = true
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
[taxonomies]
author = "authors"

